const PDFDocument = require('pdfkit');

const generatePDFReport = (analyticsData, dateRange, generatedBy) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, size: 'A4' });
            const buffers = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => {
                const pdfData = Buffer.concat(buffers);
                resolve(pdfData);
            });

            const { executiveSummary = {}, inventoryHealth = {}, transactionReport = {}, poReport = {}, categoryReport = {} } = analyticsData;
            
            const formatDate = (dateString) => dateString ? new Date(dateString).toLocaleDateString() : '';
            const periodStr = `${formatDate(dateRange.startDate)} – ${formatDate(dateRange.endDate)}`;
            
            const darkBg = '#020617';
            const indigo = '#4F46E5';
            const white = '#FFFFFF';
            const slate200 = '#E2E8F0';
            const slate400 = '#94A3B8';
            
            let pageNum = 0;
            const totalPages = 6;
            
            const addHeaderFooter = (pageTitle) => {
                pageNum++;
                // Header
                doc.fillColor(indigo).fontSize(10).text(`SmartShelfX Analytics Report | ${periodStr}`, 50, 30, { align: 'left' });
                // Footer
                doc.fillColor(slate400).fontSize(10).text(`Page ${pageNum} of ${totalPages} | Confidential`, 50, 800, { align: 'center' });
                doc.moveDown(2);
                
                // Section Title
                doc.rect(50, 60, doc.page.width - 100, 30).fill(indigo);
                doc.fillColor(white).fontSize(14).font('Helvetica-Bold').text(pageTitle, 60, 68);
                doc.moveDown(2);
                doc.fillColor(slate200).font('Helvetica');
            };

            // --- PAGE 1: Cover Page ---
            doc.rect(0, 0, doc.page.width, doc.page.height).fill(darkBg);
            doc.fillColor(indigo).fontSize(48).font('Helvetica-Bold').text('SmartShelfX', 0, 300, { align: 'center' });
            doc.fillColor(white).fontSize(24).font('Helvetica').text('Inventory & Analytics Report', 0, 360, { align: 'center' });
            doc.moveDown(2);
            doc.fillColor(slate400).fontSize(14).text(`Period: ${periodStr}`, { align: 'center' });
            doc.moveDown(4);
            
            doc.moveTo(200, 450).lineTo(doc.page.width - 200, 450).strokeColor(indigo).lineWidth(2).stroke();
            
            doc.moveDown(2);
            doc.fillColor(slate400).fontSize(12).text(`Generated by: ${generatedBy} | Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });
            
            // --- PAGE 2: Executive Summary ---
            doc.addPage();
            doc.rect(0, 0, doc.page.width, doc.page.height).fill(darkBg);
            addHeaderFooter('Executive Summary');
            
            const execData = [
                ['Total Products', executiveSummary.inventory?.totalProducts || 0],
                ['Total Stock Value', `Rs. ${executiveSummary.inventory?.totalStockValue?.toLocaleString() || 0}`],
                ['Retail Value', `Rs. ${executiveSummary.inventory?.totalRetailValue?.toLocaleString() || 0}`],
                ['Stockouts', executiveSummary.inventory?.outOfStockCount || 0],
                ['Low Stock', executiveSummary.inventory?.lowStockCount || 0],
            ];
            
            let startY = 120;
            execData.forEach(([metric, val]) => {
                doc.fillColor(slate400).fontSize(12).text(metric, 100, startY);
                doc.fillColor(white).fontSize(12).font('Helvetica-Bold').text(String(val), 400, startY);
                startY += 25;
                doc.moveTo(100, startY - 5).lineTo(500, startY - 5).strokeColor('#1E293B').lineWidth(1).stroke();
            });
            
            // Horizontal rule
            doc.moveTo(50, startY + 20).lineTo(doc.page.width - 50, startY + 20).strokeColor(indigo).lineWidth(1).stroke();
            
            // --- PAGE 3: Inventory Health ---
            doc.addPage();
            doc.rect(0, 0, doc.page.width, doc.page.height).fill(darkBg);
            addHeaderFooter('Inventory Health');
            
            doc.fillColor(white).fontSize(14).font('Helvetica-Bold').text('Inventory Status Distribution', 50, 110);
            doc.moveDown();
            
            const stats = [
                { s: 'IN STOCK', c: executiveSummary.inventory?.healthyStockCount || 0 },
                { s: 'LOW STOCK', c: executiveSummary.inventory?.lowStockCount || 0 },
                { s: 'OUT OF STOCK', c: executiveSummary.inventory?.outOfStockCount || 0 },
                { s: 'OVERSTOCKED', c: executiveSummary.inventory?.overstockedCount || 0 }
            ];
            
            let tableY = 140;
            doc.fillColor(indigo).fontSize(10).text('Status', 50, tableY);
            doc.text('Count', 200, tableY);
            tableY += 20;
            
            stats.forEach(st => {
                doc.fillColor(slate200).font('Helvetica').text(st.s, 50, tableY);
                doc.text(String(st.c), 200, tableY);
                tableY += 20;
            });
            
            tableY += 20;
            doc.fillColor(white).fontSize(14).font('Helvetica-Bold').text('Top Products by Value', 50, tableY);
            tableY += 25;
            
            const topProducts = (inventoryHealth.topValueProducts || []).slice(0, 10);
            doc.fillColor(indigo).fontSize(9);
            doc.text('Product', 50, tableY);
            doc.text('SKU', 250, tableY);
            doc.text('Stock', 350, tableY);
            doc.text('Value', 450, tableY);
            tableY += 20;
            
            doc.fillColor(slate200);
            topProducts.forEach(tp => {
                doc.text(tp.name.substring(0, 30), 50, tableY);
                doc.text(tp.sku, 250, tableY);
                doc.text(String(tp.currentStock), 350, tableY);
                doc.text(`Rs. ${tp.stockValue?.toLocaleString()}`, 450, tableY);
                tableY += 20;
            });
            
            // --- PAGE 4: Products Requiring Action ---
            doc.addPage();
            doc.rect(0, 0, doc.page.width, doc.page.height).fill(darkBg);
            addHeaderFooter('Products Requiring Action');
            
            doc.fillColor(white).fontSize(14).font('Helvetica-Bold').text('Out Of Stock Products', 50, 110);
            let actionY = 140;
            
            const allProducts = analyticsData.products || inventoryHealth.topValueProducts || [];
            const outOfStock = allProducts.filter(p => p.currentStock === 0).slice(0, 10);
            doc.fillColor(indigo).fontSize(9);
            doc.text('Product', 50, actionY);
            doc.text('SKU', 300, actionY);
            actionY += 20;
            
            doc.fillColor(slate200);
            outOfStock.forEach(p => {
                doc.text(p.name.substring(0, 40), 50, actionY);
                doc.text(p.sku, 300, actionY);
                actionY += 20;
            });
            
            actionY += 20;
            doc.fillColor(white).fontSize(14).font('Helvetica-Bold').text('Low Stock Products', 50, actionY);
            actionY += 30;
            
            const lowStock = allProducts.filter(p => p.currentStock > 0 && p.currentStock <= p.reorderLevel).slice(0, 10);
            doc.fillColor(indigo).fontSize(9);
            doc.text('Product', 50, actionY);
            doc.text('Stock', 300, actionY);
            doc.text('Reorder Lvl', 400, actionY);
            actionY += 20;
            
            doc.fillColor(slate200);
            lowStock.forEach(p => {
                doc.text(p.name.substring(0, 40), 50, actionY);
                doc.text(String(p.currentStock), 300, actionY);
                doc.text(String(p.reorderLevel), 400, actionY);
                actionY += 20;
            });
            
            // --- PAGE 5: Transaction Summary ---
            doc.addPage();
            doc.rect(0, 0, doc.page.width, doc.page.height).fill(darkBg);
            addHeaderFooter('Transaction Summary');
            
            const kpis = transactionReport.summary || {};
            doc.fillColor(white).fontSize(14).font('Helvetica-Bold').text('Flow KPIs', 50, 110);
            let txY = 140;
            
            const tStats = [
                ['Total Stock In', kpis.totalIn || 0],
                ['Total Stock Out', kpis.totalOut || 0],
                ['Net Movement', kpis.netMovement || 0]
            ];
            
            tStats.forEach(([l, v]) => {
                doc.fillColor(slate400).fontSize(12).text(l, 100, txY);
                doc.fillColor(white).font('Helvetica-Bold').text(String(v), 300, txY);
                txY += 20;
            });
            
            txY += 30;
            doc.fillColor(white).fontSize(14).font('Helvetica-Bold').text('Top 10 Active Products', 50, txY);
            txY += 25;
            
            const activeProducts = transactionReport.topProducts || [];
            doc.fillColor(indigo).fontSize(9);
            doc.text('Product', 50, txY);
            doc.text('Transactions', 250, txY);
            txY += 20;
            
            doc.fillColor(slate200);
            activeProducts.forEach(ap => {
                doc.text(ap.productName?.substring(0, 30) || 'N/A', 50, txY);
                doc.text(String((ap.inQty || 0) + (ap.outQty || 0)), 250, txY);
                txY += 20;
            });
            
            // --- PAGE 6: Purchase Orders ---
            doc.addPage();
            doc.rect(0, 0, doc.page.width, doc.page.height).fill(darkBg);
            addHeaderFooter('Purchase Orders & Logistics');
            
            const aiData = poReport.aiVsManual || {};
            doc.fillColor(white).fontSize(14).font('Helvetica-Bold').text('AI Impact Summary', 50, 110);
            let pY = 140;
            
            const aiLines = [
                ['AI Suggested POs', aiData.aiSuggestedCount || 0],
                ['Manual POs', aiData.manualCount || 0],
                ['AI Approv Rate', `${(aiData.aiApprovalRate || 0).toFixed(1)}%`],
                ['Savings Estimate', `Rs. ${aiData.aiSavingsEstimate?.toLocaleString() || 0}`]
            ];
            
            aiLines.forEach(([l, v]) => {
                doc.fillColor(slate400).fontSize(12).text(l, 100, pY);
                doc.fillColor(white).font('Helvetica-Bold').text(String(v), 300, pY);
                pY += 20;
            });
            
            pY += 30;
            doc.fillColor(white).fontSize(14).font('Helvetica-Bold').text('Vendor Performance', 50, pY);
            pY += 25;
            
            const vendors = poReport.vendorPerformance || [];
            doc.fillColor(indigo).fontSize(9);
            doc.text('Vendor', 50, pY);
            doc.text('POs', 200, pY);
            doc.text('Value', 250, pY);
            doc.text('Approval %', 350, pY);
            doc.text('On-Time %', 450, pY);
            pY += 20;
            
            doc.fillColor(slate200);
            vendors.forEach(v => {
                doc.text(v.vendorName?.substring(0, 25) || 'N/A', 50, pY);
                doc.text(String(v.totalPOs || 0), 200, pY);
                doc.text(`Rs. ${v.totalValue || 0}`, 250, pY);
                doc.text(`${(v.approvalRate || 0).toFixed(1)}%`, 350, pY);
                doc.text(`${(v.onTimeRate || 0).toFixed(1)}%`, 450, pY);
                pY += 20;
            });
            
            doc.end();
        } catch (error) {
            console.error('PDF generation error:', error);
            reject(error);
        }
    });
};

module.exports = {
    generatePDFReport
};
